name: Unublish NPM Package

on:
  workflow_dispatch:
    inputs:
      package_version:
        description: 'Package version to unpublish'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm unpublish $PACKAGE_VERSION
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          PACKAGE_VERSION: ${{ inputs.package_version }}
